{
  "error": "Expected code to be unreachable, but got: ('raw_tender', {'id': 'test-sam_gov-001', 'source_table': 'sam_gov', 'title': 'Test tender with spec...",
  "traceback": "Traceback (most recent call last):\n  File \"/Users/onelove/Downloads/python_normalizer/scripts/test_llm.py\", line 120, in custom_normalize_with_llm\n    output = await normalizer.agent.run(input_data)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/onelove/.pyenv/versions/3.12.3/lib/python3.12/site-packages/pydantic_ai/agent.py\", line 308, in run\n    async for _ in agent_run:\n  File \"/Users/onelove/.pyenv/versions/3.12.3/lib/python3.12/site-packages/pydantic_ai/agent.py\", line 1329, in __anext__\n    next_node = await self._graph_run.__anext__()\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/onelove/.pyenv/versions/3.12.3/lib/python3.12/site-packages/pydantic_graph/graph.py\", line 737, in __anext__\n    return await self.next(self._next_node)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/onelove/.pyenv/versions/3.12.3/lib/python3.12/site-packages/pydantic_graph/graph.py\", line 726, in next\n    self._next_node = await self.graph.next(node, history, state=state, deps=deps, infer_name=False)\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/onelove/.pyenv/versions/3.12.3/lib/python3.12/site-packages/pydantic_graph/graph.py\", line 305, in next\n    next_node = await node.run(ctx)\n                ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/onelove/.pyenv/versions/3.12.3/lib/python3.12/site-packages/pydantic_ai/_agent_graph.py\", line 261, in run\n    return await self._make_request(ctx)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/onelove/.pyenv/versions/3.12.3/lib/python3.12/site-packages/pydantic_ai/_agent_graph.py\", line 313, in _make_request\n    model_response, request_usage = await ctx.deps.model.request(\n                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/onelove/.pyenv/versions/3.12.3/lib/python3.12/site-packages/pydantic_ai/models/instrumented.py\", line 90, in request\n    response, usage = await super().request(messages, model_settings, model_request_parameters)\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/onelove/.pyenv/versions/3.12.3/lib/python3.12/site-packages/pydantic_ai/models/wrapper.py\", line 24, in request\n    return await self.wrapped.request(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/onelove/.pyenv/versions/3.12.3/lib/python3.12/site-packages/pydantic_ai/models/openai.py\", line 156, in request\n    response = await self._completions_create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/onelove/.pyenv/versions/3.12.3/lib/python3.12/site-packages/pydantic_ai/models/openai.py\", line 224, in _completions_create\n    async for msg in self._map_message(m):\n  File \"/Users/onelove/.pyenv/versions/3.12.3/lib/python3.12/site-packages/pydantic_ai/models/openai.py\", line 286, in _map_message\n    async for item in self._map_user_message(message):\n  File \"/Users/onelove/.pyenv/versions/3.12.3/lib/python3.12/site-packages/pydantic_ai/models/openai.py\", line 338, in _map_user_message\n    yield await self._map_user_prompt(part)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/onelove/.pyenv/versions/3.12.3/lib/python3.12/site-packages/pydantic_ai/models/openai.py\", line 388, in _map_user_prompt\n    assert_never(item)\n  File \"/Users/onelove/.pyenv/versions/3.12.3/lib/python3.12/typing.py\", line 2409, in assert_never\n    raise AssertionError(f\"Expected code to be unreachable, but got: {value}\")\nAssertionError: Expected code to be unreachable, but got: ('raw_tender', {'id': 'test-sam_gov-001', 'source_table': 'sam_gov', 'title': 'Test tender with spec...\n"
}